- name: install elasticsearch
  yum: name=elasticsearch state=latest

- name: copy elasticsearch configuration
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644

- name: enable and start elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
