---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
    - name: add repository
      apt:
        deb: "https://artifacts.elastic.co/packages/5.x/apt"
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        state: present


# wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
# apt-get install apt-transport-https
# echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
# apt-get install elasticsearch
# apt-get install kibana
# apt-get install openjdk-8-jre-headless
# apt-get install logstash
# /bin/systemctl enable elasticsearch.service
# /bin/systemctl enable kibana.service