# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8080, host: 11080
  config.vm.network "forwarded_port", guest: 8088, host: 9088

#  config.vm.provision "shell" do |shell|
#      shell.path = "jenkins.sh"
#    end

    Vagrant.configure("2") do |config|
      # Run Ansible from the Vagrant VM
      config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
      end
    end

end
