# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 8080, host: 9080
  config.vm.network "forwarded_port", guest: 8088, host: 9088
  config.vm.synced_folder "jenkins/", "/var/jenkins"

  config.vm.provision "shell" do |shell|
      shell.path = "jenkins.sh"
    end

  config.vm.provision "docker" do |d|
    d.run "jenkins_master",
      image: "jenkins:latest",
      args: "-u root -p 8080:8080 -p 50000:50000 -v /var/jenkins:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker",
      daemonize: true,
      privileged: true,
      restart: "always"
  end

end
