# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest_ip: "192.168.50.100", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest_ip: "192.168.50.100", guest: 5601, host: 5601
  config.vm.network "private_network", ip: "192.168.50.100"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 4096]
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.inventory_path = "ansible/inventory"
    ansible.playbook = "ansible/playbook.yml"
    ansible.limit = "elk"
    ansible.verbose = true
  end

end
