- name: load elasticsearch key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add Elastic repository
  yum_repository:
    name: Elastic
    description: Elasticsearch repo
    baseurl: https://artifacts.elastic.co/packages/5.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: install kibana
  yum: name=kibana state=latest

- name: enable and start kibana
  systemd:
    name: kibana
    enabled: yes
    state: started

- name: install elasticsearch
  yum: name=elasticsearch state=latest

- name: enable and start elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: started

- name: install logstash
  yum: name=logstash state=latest

- name: enable and start logstash
  systemd:
    name: logstash
    enabled: yes
    state: started

- name: set up mapping
  script: setupscript.sh